[package]
name = "local_fields"
version = "0.1"
lean_version = "leanprover-community/lean:3.44.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cea27692b3fdeb328a2ddba6aabf181754543184"}
